/* Escuila Mini App — static library browser (categories + files + search).
 * Data comes from data/*.json generated by utils/build_mini_data.py.
 * Opening a file always goes back to the bot chat (VIP checks stay server-side). */

(function () {
  'use strict';

  var tg = window.Telegram && window.Telegram.WebApp ? window.Telegram.WebApp : null;
  if (tg) {
    tg.ready();
    tg.expand();
  }

  var state = {
    cats: [],
    files: [],
    botUsername: '',
    stack: [{ type: 'home' }],
    searchTimer: null
  };

  var viewEl = document.getElementById('view');
  var searchEl = document.getElementById('search');
  var clearEl = document.getElementById('clearSearch');
  var toastEl = document.getElementById('toast');
  var btnBack = document.getElementById('btnBack');
  var btnHome = document.getElementById('btnHome');

  /* ─── helpers ─── */

  function haptic() {
    try { if (tg && tg.HapticFeedback) tg.HapticFeedback.selectionChanged(); } catch (e) { /* noop */ }
  }

  var toastTimer = null;
  function showToast(msg) {
    toastEl.textContent = msg;
    toastEl.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { toastEl.hidden = true; }, 2600);
  }

  function fileIcon(name) {
    var n = (name || '').toLowerCase();
    if (/\.pdf|فرض|امتحان|مراجعة/.test(n)) return '📕';
    if (/\.doc|\.docx|تلخيص|مذكرة|درس/.test(n)) return '📘';
    if (/\.jpg|\.jpeg|\.png|صورة/.test(n)) return '🖼️';
    if (/\.mp4|\.avi|فيديو/.test(n)) return '🎬';
    if (/\.mp3|صوت|تسميع/.test(n)) return '🎵';
    return '📄';
  }

  // Normalize Arabic for matching: strip diacritics, unify alef/ya/ta-marbuta forms.
  function normalize(s) {
    return (s || '')
      .replace(/[\u064B-\u0652\u0670\u0640]/g, '')
      .replace(/[أإآٱ]/g, 'ا')
      .replace(/ى/g, 'ي')
      .replace(/ئ/g, 'ي')
      .replace(/ؤ/g, 'و')
      .replace(/ة/g, 'ه')
      .toLowerCase()
      .trim();
  }

  function childrenOf(parentId) {
    return state.cats.filter(function (c) { return c.parent === parentId; });
  }

  function catById(id) {
    return state.cats.find(function (c) { return c.id === id; }) || null;
  }

  function filesIn(catId) {
    return state.files.filter(function (f) { return f.c === catId; });
  }

  /* ─── navigation ─── */

  function render() {
    var top = state.stack[state.stack.length - 1];
    btnBack.hidden = state.stack.length <= 1;

    if (tg && tg.BackButton) {
      if (state.stack.length > 1) {
        tg.BackButton.show();
        tg.BackButton.onClick(goBack);
      } else {
        tg.BackButton.hide();
      }
    }

    viewEl.scrollTop = 0;

    if (top.type === 'home') renderHome();
    else if (top.type === 'cat') renderCat(top.id);
    else if (top.type === 'search') renderSearchResults(top.q);
  }

  function push(view) {
    state.stack.push(view);
    render();
  }

  function goBack() {
    if (state.stack.length > 1) {
      state.stack.pop();
      render();
    }
  }

  function goHome() {
    haptic();
    state.stack = [{ type: 'home' }];
    searchEl.value = '';
    clearEl.hidden = true;
    render();
  }

  /* ─── views ─── */

  function cardHTML(icon, label, extraClass, chev) {
    return '<div class="icon">' + icon + '</div>' +
      '<div class="label">' + escapeHTML(label) + '</div>' +
      '<div class="chev">' + (chev || '◀') + '</div>';
  }

  function renderHome() {
    var roots = childrenOf(null);
    var html = '<div class="section-title">الأقسام</div>';
    if (!roots.length) {
      html += '<div class="empty">لا توجد أقسام بعد.<br>حدّث بيانات التطبيق من البوت.</div>';
    }
    roots.forEach(function (c) {
      html += cardButton(c);
    });
    viewEl.innerHTML = html;
  }

  function cardButton(c) {
    var div = document.createElement('button');
    div.type = 'button';
    div.className = 'card' + (c.locked ? ' locked' : '');
    div.innerHTML =
      '<div class="icon">' + (c.locked ? '🔒' : (c.icon || '📁')) + '</div>' +
      '<div class="label">' + escapeHTML(c.name) + '</div>' +
      '<div class="chev">◀</div>';
    div.addEventListener('click', function () { openCategory(c); });
    return div;
  }

  function fileRow(f) {
    var div = document.createElement('button');
    div.type = 'button';
    div.className = 'card';
    div.innerHTML =
      '<div class="icon">' + fileIcon(f.n) + '</div>' +
      '<div class="label">' + escapeHTML(f.n) + '</div>' +
      '<div class="chev">↗</div>';
    div.addEventListener('click', function () { openFile(f); });
    return div;
  }

  function openCategory(c) {
    haptic();
    if (c.locked) {
      // Exclusive content: let the bot enforce VIP/paywall in the chat.
      if (state.botUsername) {
        tg.openTelegramLink('https://t.me/' + state.botUsername);
      } else {
        showToast('هذا القسم حصري — افتح بوت Escuila للاشتراك في VIP');
      }
      return;
    }
    var subs = childrenOf(c.id);
    var files = filesIn(c.id);
    if (!subs.length && !files.length) {
      showToast('لا توجد ملفات في هذا القسم بعد');
      return;
    }
    push({ type: 'cat', id: c.id });
  }

  function renderCat(id) {
    var c = catById(id);
    var subs = childrenOf(id);
    var files = filesIn(id);

    viewEl.innerHTML = '';
    if (subs.length) {
      var t1 = document.createElement('div');
      t1.className = 'section-title';
      t1.textContent = 'الأقسام الفرعية';
      viewEl.appendChild(t1);
      subs.forEach(function (s) { viewEl.appendChild(cardButton(s)); });
    }
    if (files.length) {
      var t2 = document.createElement('div');
      t2.className = 'section-title';
      t2.textContent = 'الملفات (' + files.length + ')';
      viewEl.appendChild(t2);
      files.forEach(function (f) { viewEl.appendChild(fileRow(f)); });
    }
    if (!subs.length && !files.length) {
      viewEl.innerHTML = '<div class="empty">هذا القسم فارغ حالياً.</div>';
    }
    void c;
  }

  /* ─── file opening (always through the bot) ─── */

  function openFile(f) {
    haptic();
    if (!state.botUsername) {
      showToast('لم يتم ضبط معرّف البوت — أعد توليد البيانات');
      return;
    }
    tg.openTelegramLink('https://t.me/' + state.botUsername + '?start=file_' + f.id);
  }

  /* ─── search ─── */

  function doSearch(q) {
    q = normalize(q);
    if (!q) return [];
    var scored = [];
    state.files.forEach(function (f) {
      var n = normalize(f.n);
      var idx = n.indexOf(q);
      if (idx === -1) return;
      scored.push({ f: f, score: idx });
    });
    scored.sort(function (a, b) { return a.score - b.score; });
    return scored.slice(0, 60).map(function (s) { return s.f; });
  }

  function renderSearchResults(q) {
    var results = doSearch(q);
    viewEl.innerHTML = '';

    var meta = document.createElement('div');
    meta.className = 'result-meta';
    meta.textContent = 'نتائج البحث عن: «' + q + '» — ' + results.length + ' نتيجة';
    viewEl.appendChild(meta);

    if (!results.length) {
      viewEl.innerHTML += '<div class="empty">لا توجد نتائج.<br>جرّب كلمات أقصر.</div>';
      return;
    }
    results.forEach(function (f) { viewEl.appendChild(fileRow(f)); });
  }

  function escapeHTML(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  /* ─── events ─── */

  searchEl.addEventListener('input', function () {
    clearEl.hidden = !searchEl.value;
    clearTimeout(state.searchTimer);
    state.searchTimer = setTimeout(function () {
      var q = searchEl.value.trim();
      if (!q) {
        if (state.stack[state.stack.length - 1].type === 'search') goHome();
        return;
      }
      state.stack = [{ type: 'home' }, { type: 'search', q: q }];
      render();
    }, 220);
  });

  clearEl.addEventListener('click', function () {
    searchEl.value = '';
    clearEl.hidden = true;
    goHome();
    searchEl.focus();
  });

  btnHome.addEventListener('click', goHome);
  btnBack.addEventListener('click', function () { haptic(); goBack(); });

  /* ─── boot ─── */

  function fail(msg) {
    viewEl.innerHTML =
      '<div class="error-box">⚠️ ' + escapeHTML(msg) +
      '<br><button id="retryBtn">إعادة المحاولة</button></div>';
    document.getElementById('retryBtn').addEventListener('click', boot);
  }

  function fetchJSON(url) {
    return fetch(url).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    });
  }

  function boot() {
    viewEl.innerHTML = '<div class="loading">⏳ جارٍ التحميل…</div>';
    Promise.all([
      fetchJSON('data/categories.json'),
      fetchJSON('data/files.json'),
      fetchJSON('data/settings.json').catch(function () { return { bot_username: '' }; })
    ]).then(function (res) {
      state.cats = res[0].categories || [];
      state.files = res[1].files || [];
      state.botUsername = res[2].bot_username || '';
      state.stack = [{ type: 'home' }];
      render();
    }).catch(function () {
      fail('تعذر تحميل بيانات المكتبة. تأكد من رفع مجلد data/ مع التطبيق.');
    });
  }

  boot();
})();
