/* Escuila Mini App — v3: integrated library browser.
 * Data comes from data/*.json generated by utils/build_mini_data.py.
 * Features: category browsing, search, embedded viewer for free files,
 * local favorites/recents (localStorage), share, in-category filtering and
 * a reliable bot handoff. VIP files carry no URL — they route to the bot
 * (?start=file_<id>) where VIP/paywall checks stay enforced server-side. */

(function () {
  'use strict';

  var tg = window.Telegram && window.Telegram.WebApp ? window.Telegram.WebApp : null;
  if (tg) {
    tg.ready();
    tg.expand();
  }

  var state = {
    cats: [],
    files: [],
    fileById: {},
    botUsername: '',
    stack: [{ type: 'home' }],
    searchTimer: null,
    catFilter: 'all' // per-category chip filter: all | free | vip
  };

  var viewEl = document.getElementById('view');
  var searchEl = document.getElementById('search');
  var clearEl = document.getElementById('clearSearch');
  var toastEl = document.getElementById('toast');
  var btnBack = document.getElementById('btnBack');
  var btnHome = document.getElementById('btnHome');
  var btnFavs = document.getElementById('btnFavs');

  /* ─── data layer ─── */

  function childrenOf(parentId) {
    return state.cats.filter(function (c) { return c.parent === parentId; });
  }

  function catById(id) {
    return state.cats.find(function (c) { return c.id === id; }) || null;
  }

  function filesIn(catId) {
    return state.files.filter(function (f) { return f.c === catId; });
  }

  // total files in a category subtree (direct + nested)
  function fileCount(catId) {
    var n = filesIn(catId).length;
    childrenOf(catId).forEach(function (s) { n += fileCount(s.id); });
    return n;
  }

  // path from root to this category as category objects (for tappable breadcrumbs)
  function catPathNodes(catId) {
    var nodes = [];
    var cur = catById(catId);
    var guard = 0;
    while (cur && guard++ < 20) {
      nodes.unshift(cur);
      cur = cur.parent === null ? null : catById(cur.parent);
    }
    return nodes;
  }

  // all matches, best (earliest position) first — the view decides how many
  // to show and whether to tell the user about the rest
  function searchFiles(q) {
    var scored = [];
    state.files.forEach(function (f) {
      var n = normalize(f.n);
      var idx = n.indexOf(q);
      if (idx === -1) return;
      scored.push({ f: f, score: idx });
    });
    scored.sort(function (a, b) { return a.score - b.score; });
    return scored.map(function (s) { return s.f; });
  }

  function searchCats(q) {
    return state.cats.filter(function (c) {
      return normalize(c.name).indexOf(q) !== -1;
    }).slice(0, 20);
  }

  // Normalize Arabic for matching: strip diacritics, unify alef/ya/ta-marbuta forms.
  function normalize(s) {
    return (s || '')
      .replace(/[\u064B-\u0652\u0670\u0640]/g, '')
      .replace(/[أإآٱ]/g, 'ا')
      .replace(/ى/g, 'ي')
      .replace(/ئ/g, 'ي')
      .replace(/ؤ/g, 'و')
      .replace(/ة/g, 'ه')
      .toLowerCase()
      .trim();
  }

  /* ─── ui helpers ─── */

  function haptic(kind) {
    try {
      if (!tg || !tg.HapticFeedback) return;
      if (kind === 'light' && tg.HapticFeedback.impactOccurred) {
        tg.HapticFeedback.impactOccurred('light');
      } else {
        tg.HapticFeedback.selectionChanged();
      }
    } catch (e) { /* noop */ }
  }

  var toastTimer = null;
  function showToast(msg) {
    toastEl.textContent = msg;
    toastEl.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { toastEl.hidden = true; }, 2600);
  }

  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  /* ─── local data: favorites + recents ───
     Favorites: localStorage is the instant source of truth ({ids, t});
     Telegram CloudStorage mirrors it across the user's devices (no backend).
     Newest write wins — simple and predictable. */

  var FAV_KEY = 'escuila_favs_v2';      // {ids:[...], t: lastWriteTs}
  var FAV_LEGACY_KEY = 'escuila_favs';  // v1 plain array — read once, migrated
  var RECENT_KEY = 'escuila_recents';

  function lsGet(key, fallback) {
    try {
      var raw = window.localStorage.getItem(key);
      return raw ? JSON.parse(raw) : fallback;
    } catch (e) { return fallback; }
  }

  function lsSet(key, val) {
    try { window.localStorage.setItem(key, JSON.stringify(val)); } catch (e) { /* private mode */ }
  }

  function lsRemove(key) {
    try { window.localStorage.removeItem(key); } catch (e) { /* noop */ }
  }

  function loadFavs() {
    var v2 = lsGet(FAV_KEY, null);
    if (v2 && Array.isArray(v2.ids)) return { ids: v2.ids, t: v2.t || 0 };
    var legacy = lsGet(FAV_LEGACY_KEY, []);
    return { ids: Array.isArray(legacy) ? legacy : [], t: 0 };
  }

  function favIds() { return loadFavs().ids; }

  function isFav(id) { return favIds().indexOf(id) !== -1; }

  function toggleFav(id) {
    var fav = loadFavs();
    var i = fav.ids.indexOf(id);
    if (i === -1) {
      fav.ids.unshift(id);
      showToast('⭐ أُضيف إلى المفضلة');
    } else {
      fav.ids.splice(i, 1);
      showToast('أُزيل من المفضلة');
    }
    fav.t = Date.now();
    lsSet(FAV_KEY, fav);
    cloudSetFavs(fav);
  }

  function cloudGetFavs() {
    return new Promise(function (resolve) {
      try {
        if (!tg || !tg.CloudStorage || !tg.CloudStorage.get) return resolve(null);
        tg.CloudStorage.get('escuila_favs', function (err, val) { resolve(err ? null : val); });
      } catch (e) { resolve(null); }
    });
  }

  function cloudSetFavs(payload) {
    try {
      if (tg && tg.CloudStorage && tg.CloudStorage.set) {
        tg.CloudStorage.set('escuila_favs', JSON.stringify(payload));
      }
    } catch (e) { /* storage unavailable — local only */ }
  }

  function syncFavsFromCloud() {
    cloudGetFavs().then(function (raw) {
      var cloud = null;
      try { cloud = raw ? JSON.parse(raw) : null; } catch (e) { cloud = null; }
      var local = loadFavs();
      var localT = local.t || 0;
      var cloudT = cloud && Array.isArray(cloud.ids) ? (cloud.t || 0) : -1;
      if (cloudT > localT) {
        // cloud is newer (edited on another device) — adopt it
        lsSet(FAV_KEY, cloud);
        lsRemove(FAV_LEGACY_KEY);
        var top = state.stack[state.stack.length - 1].type;
        if (top === 'favs' || top === 'home') render();
      } else if (localT > cloudT && (localT > 0 || local.ids.length)) {
        // local is newer — publish it; a legacy-only device stamps its first
        // real write so the migration counts as an actual edit
        if (!localT) {
          local.t = Date.now();
          lsSet(FAV_KEY, local);
        }
        cloudSetFavs(local);
      }
      // equal timestamps mean identical payloads — nothing to do
    });
  }

  function filesByIds(ids) {
    return ids.map(function (id) { return state.fileById[id]; }).filter(Boolean);
  }

  function recordRecent(id) {
    var ids = lsGet(RECENT_KEY, []).filter(function (x) { return x !== id; });
    ids.unshift(id);
    lsSet(RECENT_KEY, ids.slice(0, 20));
  }

  function copyText(t) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(t);
        return;
      }
    } catch (e) { /* fall through */ }
    try {
      var ta = document.createElement('textarea');
      ta.value = t;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    } catch (e) { /* clipboard unavailable */ }
  }

  function fileIcon(name) {
    var n = (name || '').toLowerCase();
    if (/\.pdf|فرض|امتحان|مراجعة/.test(n)) return '📕';
    if (/\.doc|\.docx|تلخيص|مذكرة|درس/.test(n)) return '📘';
    if (/\.jpg|\.jpeg|\.png|صورة/.test(n)) return '🖼️';
    if (/\.mp4|\.avi|فيديو/.test(n)) return '🎬';
    if (/\.mp3|صوت|تسميع/.test(n)) return '🎵';
    return '📄';
  }

  function fileTypeLabel(name) {
    var n = (name || '').toLowerCase();
    if (/\.pdf/.test(n)) return 'ملف PDF';
    if (/\.docx|\.doc/.test(n)) return 'مستند Word';
    if (/\.jpg|\.jpeg|\.png/.test(n)) return 'صورة';
    if (/\.mp4|\.avi/.test(n)) return 'فيديو';
    if (/\.mp3/.test(n)) return 'ملف صوتي';
    return 'ملف تعليمي';
  }

  /* ─── embed helpers (viewer) ─── */

  function isImageUrl(url) {
    return /\.(jpe?g|png|webp|gif|bmp)(\?|#|$)/i.test(url);
  }

  // Google Drive/docs links need their /view… form turned into /preview to
  // render inside an iframe; returns null when no transform applies.
  function drivePreview(url) {
    var m = url.match(/drive\.google\.com\/file\/d\/([\w-]+)/);
    if (m) return 'https://drive.google.com/file/d/' + m[1] + '/preview';
    m = url.match(/drive\.google\.com\/.*[?&]id=([\w-]+)/);
    if (m) return 'https://drive.google.com/file/d/' + m[1] + '/preview';
    m = url.match(/docs\.google\.com\/(document|presentation|spreadsheets)\/d\/([\w-]+)/);
    if (m) return 'https://docs.google.com/' + m[1] + '/d/' + m[2] + '/preview';
    return null;
  }

  // Best embed URL for a public file link, or null if it should not be
  // embedded at all. Telegram pages block framing; direct PDFs go through
  // the Google Docs viewer because mobile browsers rarely render PDFs in a
  // plain iframe.
  function embedUrl(url) {
    if (!url || !/^https:\/\//i.test(url)) return null;
    if (isImageUrl(url)) return null;
    if (/^https:\/\/t\.me\//i.test(url)) return null;
    var drv = drivePreview(url);
    if (drv) return drv;
    if (/\.pdf(\?|#|$)/i.test(url)) {
      return 'https://docs.google.com/viewer?url=' + encodeURIComponent(url) + '&embedded=true';
    }
    return url;
  }

  /* ─── building blocks (always DOM nodes — never stringified) ─── */

  function catCard(c) {
    var btn = el('button', 'card' + (c.locked ? ' locked' : ''));
    btn.type = 'button';

    btn.appendChild(el('div', 'icon', c.locked ? '🔒' : (c.icon || '📁')));
    btn.appendChild(el('div', 'label', c.name));

    var meta = el('div', 'meta');
    if (!c.locked) {
      var count = fileCount(c.id);
      if (count > 0) meta.appendChild(el('span', 'badge', count + ' ملف'));
    }
    meta.appendChild(el('span', 'chev', '◀'));

    btn.appendChild(meta);
    btn.addEventListener('click', function () { openCategory(c); });
    return btn;
  }

  // three access states: free (in-app viewer), vip (exclusive, bot gate),
  // bot (free but no embeddable link — internal media id, t.me post, …)
  function fileAccess(f) {
    if (f.u) return 'free';
    return f.r === 'vip' ? 'vip' : 'bot';
  }

  function fileRow(f) {
    var btn = el('button', 'card');
    btn.type = 'button';
    btn.appendChild(el('div', 'icon', fileIcon(f.n)));
    btn.appendChild(el('div', 'label', f.n));
    var access = fileAccess(f);
    btn.appendChild(el('span', 'chip chip-' + access,
      access === 'free' ? 'مجاني' : (access === 'vip' ? 'VIP' : 'عبر البوت')));
    btn.addEventListener('click', function () { openFileDetails(f); });
    return btn;
  }

  function emptyBox(text) {
    var box = el('div', 'empty');
    box.innerHTML = text;
    return box;
  }

  /* ─── navigation ─── */

  function render() {
    var top = state.stack[state.stack.length - 1];
    var depth = state.stack.length;
    btnBack.hidden = depth <= 1;

    if (tg && tg.BackButton) {
      if (depth > 1) tg.BackButton.show();
      else tg.BackButton.hide();
    }

    viewEl.scrollTop = 0;

    if (top.type === 'home') renderHome();
    else if (top.type === 'cat') renderCat(top.id);
    else if (top.type === 'search') renderSearchResults(top.q);
    else if (top.type === 'file') renderFileDetails(top.file);
    else if (top.type === 'viewer') renderViewer(top.file);
    else if (top.type === 'favs') renderFavs();
    else if (top.type === 'locked') renderLockedInfo(top.cat);
  }

  function push(view) {
    state.stack.push(view);
    render();
  }

  function goBack() {
    if (state.stack.length > 1) {
      state.stack.pop();
      render();
    }
  }

  function goHome() {
    haptic();
    state.stack = [{ type: 'home' }];
    searchEl.value = '';
    clearEl.hidden = true;
    render();
  }

  /* ─── views ─── */

  function renderHome() {
    viewEl.innerHTML = '';
    var roots = childrenOf(null);

    var freeCount = state.files.filter(function (f) { return !!f.u; }).length;
    viewEl.appendChild(el('div', 'stat-line',
      roots.length + ' قسم · ' + state.files.length + ' ملف · ' + freeCount + ' مجاني للقراءة'));

    var favs = filesByIds(favIds());
    if (favs.length) {
      var favCard = el('button', 'card');
      favCard.type = 'button';
      favCard.appendChild(el('div', 'icon', '⭐'));
      favCard.appendChild(el('div', 'label', 'المفضلة'));
      var favMeta = el('div', 'meta');
      favMeta.appendChild(el('span', 'badge', favs.length + ' ملف'));
      favCard.appendChild(favMeta);
      favCard.addEventListener('click', function () { haptic(); push({ type: 'favs' }); });
      viewEl.appendChild(favCard);
    }

    var recents = filesByIds(lsGet(RECENT_KEY, []));
    if (recents.length) {
      viewEl.appendChild(el('div', 'section-title', 'شاهدت مؤخراً'));
      recents.slice(0, 5).forEach(function (f) { viewEl.appendChild(fileRow(f)); });
    }

    var head = el('div', 'section-title with-action');
    head.appendChild(el('span', null, 'الأقسام'));
    var refresh = el('button', 'link-btn');
    refresh.type = 'button';
    refresh.textContent = '🔄 تحديث';
    refresh.addEventListener('click', function () { haptic(); boot(); });
    head.appendChild(refresh);
    viewEl.appendChild(head);

    if (!roots.length) {
      viewEl.appendChild(emptyBox('لا توجد أقسام لعرضها.<br>اضغط «🔄 تحديث» أو تأكد من رفع ملفات البيانات.'));
      return;
    }
    roots.forEach(function (c) { viewEl.appendChild(catCard(c)); });
  }

  function renderCat(id) {
    var subs = childrenOf(id);
    var files = filesIn(id);

    viewEl.innerHTML = '';

    if (subs.length) {
      viewEl.appendChild(el('div', 'section-title', 'الأقسام الفرعية'));
      subs.forEach(function (s) { viewEl.appendChild(catCard(s)); });
    }
    if (files.length) {
      viewEl.appendChild(el('div', 'section-title', 'الملفات (' + files.length + ')'));

      var freeN = files.filter(function (f) { return !!f.u; }).length;
      if (freeN > 0 && freeN < files.length) {
        viewEl.appendChild(buildFilterBar(id, files.length, freeN));
      }

      var list = el('div', 'file-list');
      fillFileList(list, files);
      viewEl.appendChild(list);
    }
    if (!subs.length && !files.length) {
      viewEl.appendChild(emptyBox('لا توجد ملفات في هذا القسم.'));
    }
  }

  function buildFilterBar(catId, total, freeN) {
    var bar = el('div', 'chipbar');
    var opts = [
      ['all', 'الكل (' + total + ')'],
      ['free', '🟢 مجاني (' + freeN + ')'],
      ['vip', '🔒 VIP (' + (total - freeN) + ')']
    ];
    opts.forEach(function (o) {
      var chip = el('button', 'fchip' + (state.catFilter === o[0] ? ' on' : ''));
      chip.type = 'button';
      chip.textContent = o[1];
      chip.addEventListener('click', function () {
        state.catFilter = o[0];
        Array.prototype.forEach.call(bar.children, function (n) { n.classList.remove('on'); });
        chip.classList.add('on');
        var list = viewEl.querySelector('.file-list');
        if (list) fillFileList(list, filesIn(catId));
      });
      bar.appendChild(chip);
    });
    return bar;
  }

  function fillFileList(list, files) {
    list.innerHTML = '';
    files.forEach(function (f) {
      if (state.catFilter === 'free' && !f.u) return;
      if (state.catFilter === 'vip' && f.u) return;
      list.appendChild(fileRow(f));
    });
    if (!list.children.length) {
      list.appendChild(emptyBox(
        state.catFilter === 'free' ? 'لا توجد ملفات مجانية هنا.' : 'لا توجد ملفات VIP هنا.'));
    }
  }

  function openCategory(c) {
    haptic();
    state.catFilter = 'all';
    if (c.locked) {
      push({ type: 'locked', cat: c });
      return;
    }
    if (!childrenOf(c.id).length && !filesIn(c.id).length) {
      showToast('لا توجد ملفات في هذا القسم');
      return;
    }
    push({ type: 'cat', id: c.id });
  }

  function renderLockedInfo(c) {
    viewEl.innerHTML = '';

    var box = el('div', 'detail-box');
    box.appendChild(el('div', 'detail-icon', '🔒'));
    box.appendChild(el('div', 'detail-name', c.name));
    box.appendChild(el('div', 'detail-note',
      'هذا القسم حصري لأعضاء EscuilaVIP.\nالاشتراك والوصول يتم عبر بوت Escuila داخل المحادثة.'));

    var open = el('button', 'primary-btn');
    open.type = 'button';
    open.textContent = '💎 الذهاب للاشتراك في VIP';
    open.addEventListener('click', function () { openBotChat(''); });
    box.appendChild(open);

    var back = el('button', 'secondary-btn');
    back.type = 'button';
    back.textContent = '⬅️ متابعة التصفح';
    back.addEventListener('click', goBack);
    box.appendChild(back);

    viewEl.appendChild(box);
  }

  /* ─── file details (fully in-app) ─── */

  function openFileDetails(f) {
    haptic();
    recordRecent(f.id);
    push({ type: 'file', file: f });
  }

  function botFileUrl(f) {
    return 'https://t.me/' + state.botUsername + '?start=file_' + f.id;
  }

  // Open a t.me URL. openTelegramLink alone switches to the target chat
  // BEHIND the webview on some clients, forcing a manual app exit — closing
  // the app right after (closeAfter) brings the target in front immediately.
  function openTelegramUrl(url, closeAfter) {
    haptic('light');
    try {
      if (tg && tg.openTelegramLink) {
        tg.openTelegramLink(url);
        if (closeAfter) {
          setTimeout(function () { try { tg.close(); } catch (e) { /* already closed */ } }, 300);
        }
      } else {
        window.open(url, '_blank');
      }
    } catch (e) {
      window.open(url, '_blank');
    }
  }

  function openBotChat(startParam) {
    if (!state.botUsername) {
      showToast('لم يتم ضبط معرّف البوت');
      return;
    }
    openTelegramUrl('https://t.me/' + state.botUsername + (startParam ? '?start=' + startParam : ''), true);
  }

  function openInBot(f) {
    openBotChat('file_' + f.id);
  }

  function shareFile(f) {
    haptic();
    if (!state.botUsername) {
      showToast('لم يتم ضبط معرّف البوت');
      return;
    }
    var text = 'حمل «' + f.n + '» من بوت Escuila 📚';
    if (navigator.share) {
      navigator.share({ title: f.n, text: text, url: botFileUrl(f) })
        .catch(function () { /* user cancelled the share sheet */ });
    } else {
      copyText(botFileUrl(f));
      showToast('📋 تم نسخ الرابط — شاركه مع أصدقائك');
    }
  }

  function crumbRow(catId) {
    var crumb = el('div', 'crumb');
    catPathNodes(catId).forEach(function (c, i) {
      if (i) crumb.appendChild(el('span', 'crumb-sep', '‹'));
      var seg = el('button', 'crumb-btn', c.name);
      seg.type = 'button';
      seg.addEventListener('click', function () {
        haptic();
        state.catFilter = 'all';
        push({ type: 'cat', id: c.id });
      });
      crumb.appendChild(seg);
    });
    return crumb;
  }

  function favShareRow(f) {
    var row = el('div', 'btn-row');

    var favB = el('button', 'secondary-btn' + (isFav(f.id) ? ' fav-on' : ''));
    favB.type = 'button';
    favB.textContent = isFav(f.id) ? '★ في المفضلة' : '☆ أضف للمفضلة';
    favB.addEventListener('click', function () {
      toggleFav(f.id);
      render();
    });
    row.appendChild(favB);

    var shareB = el('button', 'secondary-btn');
    shareB.type = 'button';
    shareB.textContent = '📤 مشاركة';
    shareB.addEventListener('click', function () { shareFile(f); });
    row.appendChild(shareB);

    return row;
  }

  function renderFileDetails(f) {
    viewEl.innerHTML = '';

    var box = el('div', 'detail-box');
    box.appendChild(el('div', 'detail-icon', fileIcon(f.n)));
    box.appendChild(el('div', 'detail-name', f.n));
    box.appendChild(el('div', 'detail-type', fileTypeLabel(f.n)));

    var crumb = crumbRow(f.c);
    if (crumb.children.length) box.appendChild(crumb);

    // access badge mirrors the export rule: URL present == bot shows it to everyone
    var access = fileAccess(f);
    var badge = {
      free: ['detail-badge badge-free', '🟢 مجاني — يُقرأ داخل التطبيق'],
      vip: ['detail-badge badge-vip', '🔒 حصري — الوصول عبر البوت'],
      bot: ['detail-badge badge-bot', '🤖 مجاني — يُسلَّم عبر البوت']
    }[access];
    box.appendChild(el('div', badge[0], badge[1]));

    if (access === 'free' && /^https:\/\/t\.me\//i.test(f.u)) {
      // telegram pages can't be framed — hand straight to the app
      var tgOpen = el('button', 'primary-btn');
      tgOpen.type = 'button';
      tgOpen.textContent = '📱 فتح في تيليجرام';
      tgOpen.addEventListener('click', function () { openTelegramUrl(f.u, true); });
      box.appendChild(tgOpen);
      box.appendChild(favShareRow(f));
    } else if (access === 'free') {
      var read = el('button', 'primary-btn');
      read.type = 'button';
      read.textContent = '👁️ قراءة داخل التطبيق';
      read.addEventListener('click', function () {
        haptic('light');
        push({ type: 'viewer', file: f });
      });
      box.appendChild(read);

      box.appendChild(favShareRow(f));

      var inBrowser = el('button', 'secondary-btn');
      inBrowser.type = 'button';
      inBrowser.textContent = '🌐 فتح في المتصفح';
      inBrowser.addEventListener('click', function () {
        haptic('light');
        if (tg && tg.openLink) tg.openLink(f.u);
        else window.open(f.u, '_blank');
      });
      box.appendChild(inBrowser);

      var inBot = el('button', 'secondary-btn');
      inBot.type = 'button';
      inBot.textContent = '🤖 عبر البوت';
      inBot.addEventListener('click', function () { openInBot(f); });
      box.appendChild(inBot);
    } else {
      var open = el('button', 'primary-btn');
      open.type = 'button';
      open.textContent = '🤖 طلب الملف من البوت';
      open.addEventListener('click', function () { openInBot(f); });
      box.appendChild(open);

      box.appendChild(favShareRow(f));

      box.appendChild(el('div', 'detail-note', access === 'vip'
        ? 'هذا الملف حصري (VIP). يتم التحقق من اشتراكك وتسليم الملف داخل محادثة البوت.'
        : 'يتم تسليم هذا الملف داخل محادثة البوت مباشرة.'));
    }

    viewEl.appendChild(box);
  }

  /* ─── embedded viewer ─── */

  function renderViewer(f) {
    viewEl.innerHTML = '';

    var wrap = el('div', 'viewer-wrap');

    var bar = el('div', 'viewer-bar');
    bar.appendChild(el('div', 'viewer-title', f.n));
    wrap.appendChild(bar);

    var stage = el('div', 'viewer-stage');

    var spinner = el('div', 'loading viewer-loading', '⏳ جارٍ فتح الملف…');
    stage.appendChild(spinner);

    var src = embedUrl(f.u);
    if (isImageUrl(f.u)) {
      var img = document.createElement('img');
      img.className = 'viewer-img';
      img.alt = f.n;
      img.onload = function () { spinner.hidden = true; };
      img.onerror = function () {
        spinner.hidden = true;
        hint.textContent = '⚠️ تعذّر تحميل الصورة — جرّب زر الفتح في المتصفح.';
        hint.hidden = false;
      };
      img.src = f.u;
      stage.appendChild(img);
    } else if (src) {
      var frame = document.createElement('iframe');
      frame.className = 'viewer-frame';
      frame.setAttribute('allow', 'autoplay; fullscreen');
      frame.referrerPolicy = 'no-referrer';
      // X-Frame-Options refusals are invisible to JS: onload may still fire,
      // so the fallback buttons below stay visible in every case.
      frame.onload = function () { setTimeout(function () { spinner.hidden = true; }, 400); };
      frame.src = src;
      stage.appendChild(frame);
    } else {
      spinner.hidden = true;
    }
    wrap.appendChild(stage);

    var hint = el('div', 'viewer-hint',
      'لا يظهر شيء؟ بعض المصادر تمنع العرض المدمج — استخدم الأزرار أدناه.');
    hint.hidden = true;
    wrap.appendChild(hint);

    var actions = el('div', 'viewer-actions');
    var inBrowser = el('button', 'primary-btn');
    inBrowser.type = 'button';
    inBrowser.textContent = '🌐 فتح في المتصفح';
    inBrowser.addEventListener('click', function () {
      haptic();
      if (tg && tg.openLink) tg.openLink(f.u);
      else window.open(f.u, '_blank');
    });
    actions.appendChild(inBrowser);

    var inBot = el('button', 'secondary-btn');
    inBot.type = 'button';
    inBot.textContent = '🤖 عبر البوت';
    inBot.addEventListener('click', function () { openInBot(f); });
    actions.appendChild(inBot);
    wrap.appendChild(actions);

    viewEl.appendChild(wrap);

    // slow-source nudge: after 6s point the user at the fallback buttons
    setTimeout(function () {
      if (!spinner.hidden) {
        hint.hidden = false;
      }
    }, 6000);
  }

  /* ─── search ─── */

  function renderSearchResults(q) {
    viewEl.innerHTML = '';

    var files = searchFiles(q);
    var cats = searchCats(q);

    viewEl.appendChild(el('div', 'result-meta',
      'نتائج البحث عن: «' + q + '» — ' + (files.length + cats.length) + ' نتيجة'));

    if (!files.length && !cats.length) {
      viewEl.appendChild(emptyBox('لا توجد نتائج مطابقة.<br>جرّب كلمات أقصر أو مختلفة.'));
      return;
    }

    if (cats.length) {
      viewEl.appendChild(el('div', 'section-title', 'الأقسام'));
      cats.forEach(function (c) { viewEl.appendChild(catCard(c)); });
    }
    if (files.length) {
      viewEl.appendChild(el('div', 'section-title', 'الملفات'));
      files.slice(0, 60).forEach(function (f) { viewEl.appendChild(fileRow(f)); });
      if (files.length > 60) {
        viewEl.appendChild(el('div', 'result-meta',
          '✂️ تُعرض أول 60 نتيجة من أصل ' + files.length + ' — جرّب كلمات أدق لعرض البقية.'));
      }
    }
  }

  /* ─── favorites (stored on this device only) ─── */

  function renderFavs() {
    viewEl.innerHTML = '';

    var favs = filesByIds(favIds());
    viewEl.appendChild(el('div', 'section-title', '⭐ المفضلة (' + favs.length + ')'));

    if (!favs.length) {
      viewEl.appendChild(emptyBox('مفضلتك فارغة.<br>أضف الملفات عبر زر «☆ أضف للمفضلة» في صفحة الملف.'));
      return;
    }
    favs.forEach(function (f) { viewEl.appendChild(fileRow(f)); });
    viewEl.appendChild(el('div', 'detail-note', 'لإزالة ملف: افتحه ثم اضغط «★ في المفضلة».'));
  }

  /* ─── events ─── */

  searchEl.addEventListener('input', function () {
    clearEl.hidden = !searchEl.value;
    clearTimeout(state.searchTimer);
    state.searchTimer = setTimeout(function () {
      var q = searchEl.value.trim();
      if (!q) {
        if (state.stack[state.stack.length - 1].type === 'search') goHome();
        return;
      }
      state.stack = [{ type: 'home' }, { type: 'search', q: q }];
      render();
    }, 220);
  });

  clearEl.addEventListener('click', function () {
    searchEl.value = '';
    clearEl.hidden = true;
    goHome();
    searchEl.focus();
  });

  btnHome.addEventListener('click', goHome);
  btnBack.addEventListener('click', function () { haptic(); goBack(); });
  btnFavs.addEventListener('click', function () {
    haptic();
    push({ type: 'favs' });
  });

  // registered ONCE here — re-registering inside render() stacked duplicate
  // listeners, making one back-press pop several views
  if (tg && tg.BackButton) {
    tg.BackButton.onClick(function () { goBack(); });
  }

  /* ─── boot ─── */

  function fail(msg) {
    viewEl.innerHTML = '';
    var box = el('div', 'error-box');
    box.appendChild(el('div', null, '⚠️ ' + msg));
    var retry = el('button', null, 'إعادة المحاولة');
    retry.type = 'button';
    retry.addEventListener('click', boot);
    box.appendChild(retry);
    viewEl.appendChild(box);
  }

  function showSkeleton() {
    viewEl.innerHTML = '';
    for (var i = 0; i < 6; i++) viewEl.appendChild(el('div', 'skel skel-card'));
  }

  function applyColorScheme() {
    try {
      document.body.classList.toggle('dark', !!(tg && tg.colorScheme === 'dark'));
      if (tg && tg.onEvent) {
        tg.onEvent('themeChanged', function () {
          document.body.classList.toggle('dark', tg.colorScheme === 'dark');
        });
      }
    } catch (e) { /* noop */ }
  }

  function fetchJSON(url) {
    return fetch(url).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    });
  }

  // Try data/ first, then repo root (GitHub upload sometimes flattens folders).
  // v is the exported data version: identical v hits the browser cache, so
  // repeat opens cost nothing until the next export bumps it.
  function fetchFirst(file, v) {
    var q = '?v=' + v;
    return fetchJSON('data/' + file + q).catch(function () {
      return fetchJSON(file + q);
    });
  }

  function boot() {
    showSkeleton();
    applyColorScheme();
    // settings.json is tiny — fetched fresh (unique URL) to learn the data
    // version; the big files then reuse the browser cache until next export
    fetchJSON('data/settings.json?v=' + Date.now())
      .catch(function () { return fetchJSON('settings.json?v=' + Date.now()); })
      .catch(function () { return { bot_username: '', version: 0 }; })
      .then(function (s) {
        state.botUsername = s.bot_username || '';
        var v = s.version || Date.now();
        return Promise.all([
          fetchFirst('categories.json', v),
          fetchFirst('files.json', v)
        ]);
      })
      .then(function (res) {
        state.cats = res[0].categories || [];
        state.files = res[1].files || [];
        state.fileById = {};
        state.files.forEach(function (f) { state.fileById[f.id] = f; });
        state.stack = [{ type: 'home' }];
        state.catFilter = 'all';
        render();
        syncFavsFromCloud();
      })
      .catch(function () {
        fail(navigator.onLine === false
          ? 'لا يوجد اتصال بالإنترنت — تحقق من الشبكة ثم أعد المحاولة.'
          : 'حدث خطأ أثناء تحميل البيانات');
      });
  }

  boot();
})();
