/* Escuila Mini App — v5: professional educational library platform.
 * Data comes from data/*.json generated by utils/build_mini_data.py and
 * auto-synced from the bot's database (utils/sync_mini_data.py).
 *
 * Structure: 4 tabs (home / library / search / favorites) + stack navigation,
 * embedded viewer for free files, bot-mirrored VIP screen with live prices,
 * level/subject/type/access filters, cover-based file cards, local favorites
 * synced through Telegram CloudStorage, deep-link support (start_param).
 * VIP/paywall checks stay enforced in the bot — the app never holds secrets. */

(function () {
  'use strict';

  var tg = window.Telegram && window.Telegram.WebApp ? window.Telegram.WebApp : null;
  if (tg) {
    tg.ready();
    tg.expand();
  }

  var state = {
    cats: [],
    files: [],
    fileById: {},
    botUsername: '',
    starsPrice: 0,
    madPrice: 0,
    tab: 'home',
    stack: [{ type: 'home' }],
    query: '',
    searchTimer: null,
    catFilter: 'all',
    filters: { lv: '', sb: '', tp: '', ac: '' },
    startParamDone: false
  };

  var viewEl = document.getElementById('view');
  var searchEl = document.getElementById('search');
  var clearEl = document.getElementById('clearSearch');
  var toastEl = document.getElementById('toast');
  var sheetBackdrop = document.getElementById('sheet-backdrop');
  var tabButtons = Array.prototype.slice.call(document.querySelectorAll('#bottombar .tab'));

  var TAB_ROOTS = { home: 'home', library: 'library', search: 'search', favs: 'favs' };

  /* ─── ui helpers ─── */

  function haptic(kind) {
    try {
      if (!tg || !tg.HapticFeedback) return;
      if (kind === 'light' && tg.HapticFeedback.impactOccurred) {
        tg.HapticFeedback.impactOccurred('light');
      } else {
        tg.HapticFeedback.selectionChanged();
      }
    } catch (e) { /* noop */ }
  }

  var toastTimer = null;
  function showToast(msg) {
    toastEl.textContent = msg;
    toastEl.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { toastEl.hidden = true; }, 2600);
  }

  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  /* ─── local data: favorites + recents ───
     Favorites: localStorage is the instant source of truth ({ids, t});
     Telegram CloudStorage mirrors it across the user's devices (no backend).
     Newest write wins — simple and predictable. */

  var FAV_KEY = 'escuila_favs_v2';      // {ids:[...], t: lastWriteTs}
  var FAV_LEGACY_KEY = 'escuila_favs';  // v1 plain array — read once, migrated
  var RECENT_KEY = 'escuila_recents';

  function lsGet(key, fallback) {
    try {
      var raw = window.localStorage.getItem(key);
      return raw ? JSON.parse(raw) : fallback;
    } catch (e) { return fallback; }
  }

  function lsSet(key, val) {
    try { window.localStorage.setItem(key, JSON.stringify(val)); } catch (e) { /* private mode */ }
  }

  function lsRemove(key) {
    try { window.localStorage.removeItem(key); } catch (e) { /* noop */ }
  }

  function loadFavs() {
    var v2 = lsGet(FAV_KEY, null);
    if (v2 && Array.isArray(v2.ids)) return { ids: v2.ids, t: v2.t || 0 };
    var legacy = lsGet(FAV_LEGACY_KEY, []);
    return { ids: Array.isArray(legacy) ? legacy : [], t: 0 };
  }

  function favIds() { return loadFavs().ids; }

  function isFav(id) { return favIds().indexOf(id) !== -1; }

  function toggleFav(id) {
    var fav = loadFavs();
    var i = fav.ids.indexOf(id);
    if (i === -1) {
      fav.ids.unshift(id);
      showToast('⭐ أُضيف إلى المفضلة');
    } else {
      fav.ids.splice(i, 1);
      showToast('أُزيل من المفضلة');
    }
    fav.t = Date.now();
    lsSet(FAV_KEY, fav);
    cloudSetFavs(fav);
  }

  function cloudGetFavs() {
    return new Promise(function (resolve) {
      try {
        if (!tg || !tg.CloudStorage || !tg.CloudStorage.get) return resolve(null);
        tg.CloudStorage.get('escuila_favs', function (err, val) { resolve(err ? null : val); });
      } catch (e) { resolve(null); }
    });
  }

  function cloudSetFavs(payload) {
    try {
      if (tg && tg.CloudStorage && tg.CloudStorage.set) {
        tg.CloudStorage.set('escuila_favs', JSON.stringify(payload));
      }
    } catch (e) { /* storage unavailable — local only */ }
  }

  function syncFavsFromCloud() {
    cloudGetFavs().then(function (raw) {
      var cloud = null;
      try { cloud = raw ? JSON.parse(raw) : null; } catch (e) { cloud = null; }
      var local = loadFavs();
      var localT = local.t || 0;
      var cloudT = cloud && Array.isArray(cloud.ids) ? (cloud.t || 0) : -1;
      if (cloudT > localT) {
        // cloud is newer (edited on another device) — adopt it
        lsSet(FAV_KEY, cloud);
        lsRemove(FAV_LEGACY_KEY);
        var top = state.stack[state.stack.length - 1].type;
        if (top === 'favs' || top === 'home') render();
      } else if (localT > cloudT && (localT > 0 || local.ids.length)) {
        // local is newer — publish it; a legacy-only device stamps its first
        // real write so the migration counts as an actual edit
        if (!localT) {
          local.t = Date.now();
          lsSet(FAV_KEY, local);
        }
        cloudSetFavs(local);
      }
      // equal timestamps mean identical payloads — nothing to do
    });
  }

  function filesByIds(ids) {
    return ids.map(function (id) { return state.fileById[id]; }).filter(Boolean);
  }

  function recordRecent(id) {
    var ids = lsGet(RECENT_KEY, []).filter(function (x) { return x !== id; });
    ids.unshift(id);
    lsSet(RECENT_KEY, ids.slice(0, 20));
  }

  function copyText(t) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(t);
        return;
      }
    } catch (e) { /* fall through */ }
    try {
      var ta = document.createElement('textarea');
      ta.value = t;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    } catch (e) { /* clipboard unavailable */ }
  }

  /* ─── data layer ─── */

  function childrenOf(parentId) {
    return state.cats.filter(function (c) { return c.parent === parentId; });
  }

  function catById(id) {
    return state.cats.find(function (c) { return c.id === id; }) || null;
  }

  function filesIn(catId) {
    return state.files.filter(function (f) { return f.c === catId; });
  }

  // total files in a category subtree (direct + nested)
  function fileCount(catId) {
    var n = filesIn(catId).length;
    childrenOf(catId).forEach(function (s) { n += fileCount(s.id); });
    return n;
  }

  // path from root to this category as category objects (for breadcrumbs)
  function catPathNodes(catId) {
    var nodes = [];
    var cur = catById(catId);
    var guard = 0;
    while (cur && guard++ < 20) {
      nodes.unshift(cur);
      cur = cur.parent === null ? null : catById(cur.parent);
    }
    return nodes;
  }

  // Normalize Arabic for matching: strip diacritics, unify alef/ya/ta-marbuta forms.
  function normalize(s) {
    return (s || '')
      .replace(/[\u064B-\u0652\u0670\u0640]/g, '')
      .replace(/[أإآٱ]/g, 'ا')
      .replace(/ى/g, 'ي')
      .replace(/ئ/g, 'ي')
      .replace(/ؤ/g, 'و')
      .replace(/ة/g, 'ه')
      .toLowerCase()
      .trim();
  }

  // all matches, best (earliest position) first — the view decides how many
  // to show and whether to tell the user about the rest
  function searchFiles(q) {
    var scored = [];
    state.files.forEach(function (f) {
      var n = normalize(f.n);
      var idx = n.indexOf(q);
      if (idx === -1) return;
      scored.push({ f: f, score: idx });
    });
    scored.sort(function (a, b) { return a.score - b.score; });
    return scored.map(function (s) { return s.f; });
  }

  function searchCats(q) {
    return state.cats.filter(function (c) {
      return normalize(c.name).indexOf(q) !== -1;
    }).slice(0, 20);
  }

  /* ─── file metadata: type / access / level / subject ─── */

  var TYPES = [
    { key: 'pdf', label: 'PDF', icon: '📕' },
    { key: 'doc', label: 'مستند', icon: '📘' },
    { key: 'img', label: 'صورة', icon: '🖼️' },
    { key: 'vid', label: 'فيديو', icon: '🎬' },
    { key: 'aud', label: 'صوت', icon: '🎵' },
    { key: 'gen', label: 'ملف', icon: '📄' }
  ];

  function typeOf(f) {
    var n = (f.n || '').toLowerCase();
    if (/\.pdf|فرض|امتحان|مراجعة/.test(n)) return TYPES[0];
    if (/\.doc|\.docx|تلخيص|مذكرة|درس/.test(n)) return TYPES[1];
    if (/\.jpg|\.jpeg|\.png|صورة/.test(n)) return TYPES[2];
    if (/\.mp4|\.avi|فيديو/.test(n)) return TYPES[3];
    if (/\.mp3|صوت|تسميع/.test(n)) return TYPES[4];
    return TYPES[5];
  }

  // three access states: free (in-app viewer), vip (exclusive, bot gate),
  // bot (free but no embeddable link — internal media id, t.me post, …)
  function fileAccess(f) {
    if (f.u) return 'free';
    return f.r === 'vip' ? 'vip' : 'bot';
  }

  var ACCESS_LABEL = {
    free: 'مجاني',
    vip: 'VIP',
    bot: 'عبر البوت'
  };

  var LEVEL_ORDER = ['الأول', 'الثاني', 'الثالث', 'الرابع', 'الخامس', 'السادس'];
  var SECONDARY_ORDER = ['الأول', 'الثاني', 'الثالث'];

  function levelRank(lv) {
    // collège levels ("الثالث إعدادي") sort after all primary levels
    if (lv.indexOf('إعدادي') !== -1) {
      for (var j = 0; j < SECONDARY_ORDER.length; j++) {
        if (lv.indexOf(SECONDARY_ORDER[j]) !== -1) return 6 + j;
      }
      return 6;
    }
    for (var i = 0; i < LEVEL_ORDER.length; i++) {
      if (lv.indexOf(LEVEL_ORDER[i]) !== -1) return i;
    }
    return 9;
  }

  function distinctValues(key, sorter) {
    var seen = {};
    state.files.forEach(function (f) {
      if (f[key]) seen[f[key]] = true;
    });
    var list = Object.keys(seen);
    return sorter ? list.sort(sorter) : list.sort();
  }

  function levelValues() {
    return distinctValues('lv', function (a, b) { return levelRank(a) - levelRank(b); });
  }

  function subjectValues() {
    return distinctValues('sb');
  }

  function popularFiles(limit) {
    return state.files.filter(function (f) { return f.k > 0; })
      .sort(function (a, b) { return b.k - a.k; })
      .slice(0, limit || 8);
  }

  function recentAddedFiles(limit) {
    return state.files.slice()
      .sort(function (a, b) { return b.id - a.id; })
      .slice(0, limit || 8);
  }

  // local personalization without user identity: files from the categories
  // of the user's recently opened files, excluding what they already opened
  function recommendedFiles(limit) {
    var recents = filesByIds(lsGet(RECENT_KEY, []));
    if (!recents.length) return [];
    var catIds = {};
    recents.forEach(function (f) {
      var c = catById(f.c);
      if (c && !c.locked) catIds[c.id] = true;
    });
    var opened = {};
    recents.forEach(function (f) { opened[f.id] = true; });
    return state.files.filter(function (f) {
      return !opened[f.id] && catIds[f.c];
    }).slice(0, limit || 8);
  }

  function applyFilters(files) {
    var ft = state.filters;
    return files.filter(function (f) {
      if (ft.lv && f.lv !== ft.lv) return false;
      if (ft.sb && f.sb !== ft.sb) return false;
      if (ft.tp && typeOf(f).key !== ft.tp) return false;
      if (ft.ac && fileAccess(f) !== ft.ac) return false;
      return true;
    });
  }

  function filtersActive() {
    var ft = state.filters;
    return !!(ft.lv || ft.sb || ft.tp || ft.ac);
  }

  /* ─── telegram helpers ─── */

  function botFileUrl(f) {
    return 'https://t.me/' + state.botUsername + '?start=file_' + f.id;
  }

  // Open a t.me URL. openTelegramLink alone switches to the target chat
  // BEHIND the webview on some clients, forcing a manual app exit — closing
  // the app right after (closeAfter) brings the target in front immediately.
  function openTelegramUrl(url, closeAfter) {
    haptic('light');
    try {
      if (tg && tg.openTelegramLink) {
        tg.openTelegramLink(url);
        if (closeAfter) {
          setTimeout(function () { try { tg.close(); } catch (e) { /* already closed */ } }, 300);
        }
      } else {
        window.open(url, '_blank');
      }
    } catch (e) {
      window.open(url, '_blank');
    }
  }

  function openBotChat(startParam) {
    if (!state.botUsername) {
      showToast('لم يتم ضبط معرّف البوت');
      return;
    }
    openTelegramUrl('https://t.me/' + state.botUsername + (startParam ? '?start=' + startParam : ''), true);
  }

  function openInBot(f) {
    openBotChat('file_' + f.id);
  }

  function shareFile(f) {
    haptic('light');
    if (!state.botUsername) {
      showToast('لم يتم ضبط معرّف البوت');
      return;
    }
    var text = 'حمل «' + f.n + '» من بوت Escuila 📚';
    if (navigator.share) {
      navigator.share({ title: f.n, text: text, url: botFileUrl(f) })
        .catch(function () { /* user cancelled the share sheet */ });
    } else {
      copyText(botFileUrl(f));
      showToast('📋 تم نسخ الرابط — شاركه مع أصدقائك');
    }
  }

  /* MainButton: single registered handler, per-view action (native feel) */
  var mainBtnAction = null;
  if (tg && tg.MainButton) {
    tg.MainButton.onClick(function () { if (mainBtnAction) mainBtnAction(); });
  }

  function setMainButton(text, action) {
    mainBtnAction = action || null;
    try {
      if (!tg || !tg.MainButton) return;
      if (!text) { tg.MainButton.hide(); return; }
      tg.MainButton.setText(text);
      tg.MainButton.show();
    } catch (e) { /* older clients */ }
  }

  /* ─── embed helpers (viewer) ─── */

  function isImageUrl(url) {
    return /\.(jpe?g|png|webp|gif|bmp)(\?|#|$)/i.test(url);
  }

  // Google Drive/docs links need their /view… form turned into /preview to
  // render inside an iframe; returns null when no transform applies.
  function drivePreview(url) {
    var m = url.match(/drive\.google\.com\/file\/d\/([\w-]+)/);
    if (m) return 'https://drive.google.com/file/d/' + m[1] + '/preview';
    m = url.match(/drive\.google\.com\/.*[?&]id=([\w-]+)/);
    if (m) return 'https://drive.google.com/file/d/' + m[1] + '/preview';
    m = url.match(/docs\.google\.com\/(document|presentation|spreadsheets)\/d\/([\w-]+)/);
    if (m) return 'https://docs.google.com/' + m[1] + '/d/' + m[2] + '/preview';
    return null;
  }

  // Best embed URL for a public file link, or null if it should not be
  // embedded at all. Telegram pages block framing; direct PDFs go through
  // the Google Docs viewer because mobile browsers rarely render PDFs in a
  // plain iframe.
  function embedUrl(url) {
    if (!url || !/^https:\/\//i.test(url)) return null;
    if (isImageUrl(url)) return null;
    if (/^https:\/\/t\.me\//i.test(url)) return null;
    var drv = drivePreview(url);
    if (drv) return drv;
    if (/\.pdf(\?|#|$)/i.test(url)) {
      return 'https://docs.google.com/viewer?url=' + encodeURIComponent(url) + '&embedded=true';
    }
    return url;
  }

  /* ─── building blocks (always DOM nodes — never stringified) ─── */

  function coverEl(f, small) {
    var t = typeOf(f);
    var cover = el('div', 'cover cover-' + t.key + (small ? ' cover-sm' : ''));
    cover.appendChild(el('span', 'cover-icon', t.icon));
    cover.appendChild(el('span', 'cover-type', t.label));
    return cover;
  }

  function accessChip(f) {
    var access = fileAccess(f);
    return el('span', 'chip chip-' + access, ACCESS_LABEL[access]);
  }

  function metaLine(f) {
    var parts = [];
    if (f.lv) parts.push(f.lv);
    if (f.sb) parts.push(f.sb);
    return parts.join(' · ');
  }

  function catCard(c) {
    var btn = el('button', 'card' + (c.locked ? ' locked' : ''));
    btn.type = 'button';

    btn.appendChild(el('div', 'icon', c.locked ? '🔒' : (c.icon || '📁')));
    btn.appendChild(el('div', 'label', c.name));

    var meta = el('div', 'meta');
    if (!c.locked) {
      var count = fileCount(c.id);
      if (count > 0) meta.appendChild(el('span', 'badge', count + ' ملف'));
    }
    meta.appendChild(el('span', 'chev', '◀'));

    btn.appendChild(meta);
    btn.addEventListener('click', function () { openCategory(c); });
    return btn;
  }

  // list card: cover thumbnail + name + meta + access chip
  function fileRow(f) {
    var btn = el('button', 'fcard');
    btn.type = 'button';

    btn.appendChild(coverEl(f, true));

    var info = el('div', 'fcard-info');
    info.appendChild(el('div', 'fcard-name', f.n));
    var meta = metaLine(f);
    if (meta) info.appendChild(el('div', 'fcard-meta', meta));
    info.appendChild(accessChip(f));
    btn.appendChild(info);

    btn.appendChild(el('div', 'chev', '◀'));
    btn.addEventListener('click', function () { openFileDetails(f); });
    return btn;
  }

  // small horizontal-scroll card (home rows)
  function miniCard(f) {
    var btn = el('button', 'mini-card');
    btn.type = 'button';
    btn.appendChild(coverEl(f, false));
    btn.appendChild(el('div', 'mini-name', f.n));
    btn.addEventListener('click', function () { openFileDetails(f); });
    return btn;
  }

  function hScrollRow(title, files) {
    var wrap = el('div', 'section');
    var head = el('div', 'section-head');
    head.appendChild(el('div', 'section-title', title));
    wrap.appendChild(head);
    var row = el('div', 'row-scroll');
    files.forEach(function (f) { row.appendChild(miniCard(f)); });
    wrap.appendChild(row);
    return wrap;
  }

  function chipRow(title, values, onPick) {
    if (!values.length) return null;
    var wrap = el('div', 'section');
    wrap.appendChild(el('div', 'section-title', title));
    var row = el('div', 'row-scroll');
    values.forEach(function (v) {
      var chip = el('button', 'fchip', v);
      chip.type = 'button';
      chip.addEventListener('click', function () { onPick(v); });
      row.appendChild(chip);
    });
    wrap.appendChild(row);
    return wrap;
  }

  function emptyBox(text) {
    var box = el('div', 'empty');
    box.innerHTML = text;
    return box;
  }

  function sectionTitle(text, trailing) {
    var head = el('div', 'section-title with-action');
    head.appendChild(el('span', null, text));
    if (trailing) head.appendChild(trailing);
    return head;
  }

  // renders long lists in batches with a "show more" control
  function renderBatched(container, items, itemBuilder, batch) {
    batch = batch || 40;
    var shown = 0;
    function appendNext() {
      var slice = items.slice(shown, shown + batch);
      slice.forEach(function (it) { container.appendChild(itemBuilder(it)); });
      shown += slice.length;
      if (shown < items.length) {
        var more = el('button', 'secondary-btn more-btn',
          'عرض المزيد (' + (items.length - shown) + ' متبقٍ)');
        more.type = 'button';
        more.addEventListener('click', function () {
          haptic();
          more.remove();
          appendNext();
        });
        container.appendChild(more);
      }
    }
    appendNext();
  }

  /* ─── navigation (tabs + stack) ─── */

  function updateTabbar() {
    tabButtons.forEach(function (b) {
      b.classList.toggle('active', b.getAttribute('data-tab') === state.tab);
    });
  }

  function switchTab(tab, opts) {
    haptic();
    state.tab = tab;
    state.stack = [{ type: TAB_ROOTS[tab] }];
    render();
    updateTabbar();
    if (tab === 'search' && !(opts && opts.noFocus)) searchEl.focus();
  }

  function render() {
    var top = state.stack[state.stack.length - 1];
    var depth = state.stack.length;

    setMainButton(null);

    if (tg && tg.BackButton) {
      if (depth > 1) tg.BackButton.show();
      else tg.BackButton.hide();
    }

    viewEl.scrollTop = 0;

    if (top.type === 'home') renderHome();
    else if (top.type === 'library') renderLibrary();
    else if (top.type === 'search') renderSearch();
    else if (top.type === 'favs') renderFavs();
    else if (top.type === 'cat') renderCat(top.id);
    else if (top.type === 'file') renderFileDetails(top.file);
    else if (top.type === 'viewer') renderViewer(top.file);
    else if (top.type === 'vip') renderVip();
    else if (top.type === 'results') renderResults(top.source, top.q);
    else if (top.type === 'locked') renderLockedInfo(top.cat);
  }

  function push(view) {
    state.stack.push(view);
    render();
  }

  function goBack() {
    if (state.stack.length > 1) {
      state.stack.pop();
      render();
    }
  }

  /* ─── home tab ─── */

  function renderHome() {
    viewEl.innerHTML = '';

    var freeCount = state.files.filter(function (f) { return !!f.u; }).length;
    viewEl.appendChild(el('div', 'stat-line',
      state.cats.length + ' قسم · ' + state.files.length + ' ملف · ' + freeCount + ' للقراءة المباشرة'));

    // continue — the file the user opened last, one tap away
    var last = filesByIds(lsGet(RECENT_KEY, []))[0];
    if (last) {
      var cont = el('button', 'continue-card');
      cont.type = 'button';
      cont.appendChild(coverEl(last, true));
      var cinfo = el('div', 'fcard-info');
      cinfo.appendChild(el('div', 'continue-label', '⏱ متابعة'));
      cinfo.appendChild(el('div', 'fcard-name', last.n));
      cont.appendChild(cinfo);
      cont.appendChild(el('div', 'chev', '◀'));
      cont.addEventListener('click', function () {
        haptic('light');
        var access = fileAccess(last);
        if (access === 'free' && !/^https:\/\/t\.me\//i.test(last.u)) {
          push({ type: 'viewer', file: last });
        } else {
          push({ type: 'file', file: last });
        }
      });
      viewEl.appendChild(cont);
    }

    var recent = recentAddedFiles(8);
    if (recent.length) viewEl.appendChild(hScrollRow('🆕 أُضيف حديثاً', recent));

    var popular = popularFiles(8);
    if (popular.length) viewEl.appendChild(hScrollRow('🔥 الأكثر استخداماً', popular));

    var reco = recommendedFiles(8);
    if (reco.length) viewEl.appendChild(hScrollRow('✨ مقترح لك', reco));

    var levels = chipRow('🎓 حسب المستوى', levelValues(), function (lv) {
      state.filters = { lv: lv, sb: '', tp: '', ac: '' };
      push({ type: 'results', source: 'all' });
    });
    if (levels) viewEl.appendChild(levels);

    var subjects = chipRow('📚 حسب المادة', subjectValues(), function (sb) {
      state.filters = { lv: '', sb: sb, tp: '', ac: '' };
      push({ type: 'results', source: 'all' });
    });
    if (subjects) viewEl.appendChild(subjects);

    var lockedCats = state.cats.filter(function (c) { return c.locked; });
    if (lockedCats.length) {
      var vipCard = el('button', 'vip-banner');
      vipCard.type = 'button';
      vipCard.appendChild(el('div', 'vip-icon', '💎'));
      var vinfo = el('div', 'vip-info');
      vinfo.appendChild(el('div', 'vip-title', 'محتوى EscuilaVIP'));
      vinfo.appendChild(el('div', 'vip-sub', lockedCats.length + ' قسماً حصرياً + ملفات مميزة'));
      vipCard.appendChild(vinfo);
      vipCard.appendChild(el('div', 'chev', '◀'));
      vipCard.addEventListener('click', function () { haptic('light'); push({ type: 'vip' }); });
      viewEl.appendChild(vipCard);
    }

    var allBtn = el('button', 'secondary-btn');
    allBtn.type = 'button';
    allBtn.textContent = '📚 استعرض كل الأقسام';
    allBtn.addEventListener('click', function () { switchTab('library', { noFocus: true }); });
    viewEl.appendChild(allBtn);
  }

  /* ─── library tab ─── */

  function renderLibrary() {
    viewEl.innerHTML = '';

    var browseAll = el('button', 'card');
    browseAll.type = 'button';
    browseAll.appendChild(el('div', 'icon', '🗂️'));
    browseAll.appendChild(el('div', 'label', 'كل الملفات مع الفلاتر'));
    browseAll.appendChild(el('div', 'meta'));
    browseAll.addEventListener('click', function () {
      haptic('light');
      state.filters = { lv: '', sb: '', tp: '', ac: '' };
      push({ type: 'results', source: 'all' });
    });
    viewEl.appendChild(browseAll);

    var refresh = el('button', 'link-btn');
    refresh.type = 'button';
    refresh.textContent = '🔄 تحديث';
    refresh.addEventListener('click', function () { haptic(); boot(); });
    viewEl.appendChild(sectionTitle('الأقسام', refresh));

    var roots = childrenOf(null);
    if (!roots.length) {
      viewEl.appendChild(emptyBox('لا توجد أقسام لعرضها.<br>اضغط «🔄 تحديث» أو تأكد من رفع ملفات البيانات.'));
      return;
    }
    roots.forEach(function (c) { viewEl.appendChild(catCard(c)); });
  }

  /* ─── category view ─── */

  function openCategory(c) {
    haptic();
    state.catFilter = 'all';
    if (c.locked) {
      push({ type: 'locked', cat: c });
      return;
    }
    if (!childrenOf(c.id).length && !filesIn(c.id).length) {
      showToast('لا توجد ملفات في هذا القسم');
      return;
    }
    push({ type: 'cat', id: c.id });
  }

  function renderCat(id) {
    var subs = childrenOf(id);
    var files = filesIn(id);
    var cat = catById(id);

    viewEl.innerHTML = '';

    if (cat) {
      var nodes = catPathNodes(id);
      if (nodes.length > 1) {
        var crumb = el('div', 'crumb');
        nodes.forEach(function (c, i) {
          if (i) crumb.appendChild(el('span', 'crumb-sep', '‹'));
          var seg = el('button', 'crumb-btn', c.name);
          seg.type = 'button';
          if (i < nodes.length - 1) {
            seg.addEventListener('click', function () {
              haptic();
              state.catFilter = 'all';
              push({ type: 'cat', id: c.id });
            });
          }
          crumb.appendChild(seg);
        });
        viewEl.appendChild(crumb);
      }
    }

    if (subs.length) {
      viewEl.appendChild(el('div', 'section-title', 'الأقسام الفرعية'));
      subs.forEach(function (s) { viewEl.appendChild(catCard(s)); });
    }
    if (files.length) {
      var filterBtn = el('button', 'link-btn');
      filterBtn.type = 'button';
      filterBtn.textContent = '⚙️ فلترة';
      filterBtn.addEventListener('click', function () { openFilterSheet(files, 'cat'); });
      viewEl.appendChild(sectionTitle('الملفات (' + files.length + ')', filterBtn));

      var freeN = files.filter(function (f) { return !!f.u; }).length;
      if (freeN > 0 && freeN < files.length) {
        viewEl.appendChild(buildCatAccessBar(files));
      }

      var list = el('div', 'file-list');
      fillCatList(list, files);
      viewEl.appendChild(list);
    }
    if (!subs.length && !files.length) {
      viewEl.appendChild(emptyBox('هذا القسم فارغ حالياً.<br>سيظهر المحتوى هنا فور إضافته من لوحة الإدارة.'));
    }
  }

  function buildCatAccessBar(files) {
    var bar = el('div', 'chipbar');
    var freeN = files.filter(function (f) { return !!f.u; }).length;
    var opts = [
      ['all', 'الكل (' + files.length + ')'],
      ['free', '🟢 مجاني (' + freeN + ')'],
      ['rest', '🔒 للبوت (' + (files.length - freeN) + ')']
    ];
    opts.forEach(function (o) {
      var chip = el('button', 'fchip' + (state.catFilter === o[0] ? ' on' : ''));
      chip.type = 'button';
      chip.textContent = o[1];
      chip.addEventListener('click', function () {
        state.catFilter = o[0];
        Array.prototype.forEach.call(bar.children, function (n) { n.classList.remove('on'); });
        chip.classList.add('on');
        var list = viewEl.querySelector('.file-list');
        if (list) fillCatList(list, files);
      });
      bar.appendChild(chip);
    });
    return bar;
  }

  function fillCatList(list, files) {
    list.innerHTML = '';
    files.forEach(function (f) {
      var access = fileAccess(f);
      if (state.catFilter === 'free' && access !== 'free') return;
      if (state.catFilter === 'rest' && access === 'free') return;
      list.appendChild(fileRow(f));
    });
    if (!list.children.length) {
      list.appendChild(emptyBox('لا توجد ملفات مطابقة هنا.'));
    }
  }

  /* ─── search tab ─── */

  function renderSearch() {
    viewEl.innerHTML = '';
    var q = normalize(state.query);

    if (!q) {
      viewEl.appendChild(emptyBox('🔍 اكتب في خانة البحث بالأعلى<br>اسم درس أو فرض أو مادة…'));
      var popular = popularFiles(6);
      if (popular.length) viewEl.appendChild(hScrollRow('🔥 الأكثر استخداماً', popular));
      return;
    }

    var files = applyFilters(searchFiles(q));
    var cats = state.filtersActive() ? [] : searchCats(q);

    var meta = el('div', 'result-meta',
      'نتائج البحث عن: «' + state.query + '» — ' + (files.length + cats.length) + ' نتيجة');
    viewEl.appendChild(meta);

    if (filtersActive()) {
      viewEl.appendChild(activeChipsRow());
    }

    var filterBtn = el('button', 'secondary-btn filter-open');
    filterBtn.type = 'button';
    filterBtn.textContent = '⚙️ تصفية النتائج';
    filterBtn.addEventListener('click', function () {
      openFilterSheet(searchFiles(q), 'search', state.query);
    });
    viewEl.appendChild(filterBtn);

    if (!files.length && !cats.length) {
      viewEl.appendChild(emptyBox('لا توجد نتائج مطابقة.<br>جرّب كلمات أقصر أو اسم المادة.'));
      return;
    }

    if (cats.length) {
      viewEl.appendChild(el('div', 'section-title', 'الأقسام'));
      cats.forEach(function (c) { viewEl.appendChild(catCard(c)); });
    }
    if (files.length) {
      viewEl.appendChild(el('div', 'section-title', 'الملفات'));
      var list = el('div', 'file-list');
      renderBatched(list, files, fileRow, 40);
      viewEl.appendChild(list);
      if (files.length > 40) {
        viewEl.appendChild(el('div', 'result-meta',
          '✂️ تُعرض النتائج على دفعات — استخدم الفلاتر لتضييقها.'));
      }
    }
  }

  function activeChipsRow() {
    var ft = state.filters;
    var bar = el('div', 'chipbar');
    Object.keys(ft).forEach(function (k) {
      if (!ft[k]) return;
      var label = k === 'lv' || k === 'sb' ? ft[k]
        : (k === 'tp' ? (TYPES.find(function (t) { return t.key === ft[k]; }) || {}).label || ft[k]
          : ACCESS_LABEL[ft[k]] || ft[k]);
      var chip = el('button', 'fchip on', label + ' ✕');
      chip.type = 'button';
      chip.setAttribute('aria-label', 'إزالة الفلتر');
      chip.addEventListener('click', function () {
        state.filters[k] = '';
        render();
      });
      bar.appendChild(chip);
    });
    var clear = el('button', 'fchip', 'مسح الكل');
    clear.type = 'button';
    clear.addEventListener('click', function () {
      state.filters = { lv: '', sb: '', tp: '', ac: '' };
      render();
    });
    bar.appendChild(clear);
    return bar;
  }

  /* ─── filtered results view ─── */

  function renderResults(source) {
    viewEl.innerHTML = '';

    var base = source === 'search' ? searchFiles(normalize(state.query)) : state.files;
    var files = applyFilters(base);

    var head = source === 'search'
      ? 'نتائج البحث المفلترة'
      : 'كل الملفات';
    var refresh = el('button', 'link-btn');
    refresh.type = 'button';
    refresh.textContent = '⚙️ فلترة';
    refresh.addEventListener('click', function () { openFilterSheet(base, source, state.query); });
    viewEl.appendChild(sectionTitle(head + ' (' + files.length + ')', refresh));

    viewEl.appendChild(activeChipsRow());

    if (!files.length) {
      viewEl.appendChild(emptyBox('لا توجد ملفات مطابقة للفلاتر المختارة.<br>جرّب إزالة بعض الفلاتر.'));
      return;
    }

    var list = el('div', 'file-list');
    renderBatched(list, files, fileRow, 40);
    viewEl.appendChild(list);
  }

  /* ─── filter sheet (bottom sheet) ─── */

  function openFilterSheet(baseFiles, source, q) {
    closeSheet();
    haptic();

    var lvSet = {}, sbSet = {}, tpSet = {}, acSet = {};
    baseFiles.forEach(function (f) {
      if (f.lv) lvSet[f.lv] = true;
      if (f.sb) sbSet[f.sb] = true;
      tpSet[typeOf(f).key] = true;
      acSet[fileAccess(f)] = true;
    });

    var sheet = el('div', 'sheet');
    var head = el('div', 'sheet-head');
    head.appendChild(el('div', 'sheet-title', '⚙️ تصفية'));
    var closeBtn = el('button', 'sheet-close', '✕');
    closeBtn.type = 'button';
    closeBtn.setAttribute('aria-label', 'إغلاق');
    head.appendChild(closeBtn);
    sheet.appendChild(head);

    function group(label, values, current, key, orderFn) {
      var keys = Object.keys(values);
      if (!keys.length) return;
      var g = el('div', 'fgroup');
      g.appendChild(el('div', 'fgroup-title', label));
      var row = el('div', 'fgroup-chips');
      keys.sort(orderFn).forEach(function (v) {
        var chip = el('button', 'fchip' + (current[k] === v ? ' on' : ''));
        chip.type = 'button';
        chip.textContent = v;
        chip.addEventListener('click', function () {
          haptic();
          current[k] = current[k] === v ? '' : v;
          Array.prototype.forEach.call(row.children, function (n) { n.classList.remove('on'); });
          if (current[k] === v) chip.classList.add('on');
          updateCount();
        });
        row.appendChild(chip);
      });
      g.appendChild(row);
      sheet.appendChild(g);
    }

    var draft = { lv: state.filters.lv, sb: state.filters.sb, tp: state.filters.tp, ac: state.filters.ac };
    var draftFiles = function () { return baseFiles.filter(function (f) {
      if (draft.lv && f.lv !== draft.lv) return false;
      if (draft.sb && f.sb !== draft.sb) return false;
      if (draft.tp && typeOf(f).key !== draft.tp) return false;
      if (draft.ac && fileAccess(f) !== draft.ac) return false;
      return true;
    }); };

    var countLine = el('div', 'sheet-count', '');
    var applyBtn = el('button', 'primary-btn sheet-apply');
    applyBtn.type = 'button';
    function updateCount() {
      countLine.textContent = draftFiles().length + ' ملف مطابق';
    }

    group('المستوى', lvSet, draft, 'lv', function (a, b) { return levelRank(a) - levelRank(b); });
    group('المادة', sbSet, draft, 'sb');
    group('النوع', tpSet, draft, 'tp', function (a, b) {
      return TYPES.findIndex(function (t) { return t.key === a; })
        - TYPES.findIndex(function (t) { return t.key === b; });
    });
    group('الوصول', acSet, draft, 'ac', function (a, b) {
      return ['free', 'bot', 'vip'].indexOf(a) - ['free', 'bot', 'vip'].indexOf(b);
    });
    // chip labels for type/access groups use canonical labels
    Array.prototype.forEach.call(sheet.querySelectorAll('.fgroup-chips'), function () { /* noop */ });

    if (!sheet.querySelector('.fgroup')) {
      viewEl.innerHTML = '';
      viewEl.appendChild(emptyBox('لا تتوفر فلاتر لهذه القائمة.'));
      return;
    }

    sheet.appendChild(countLine);
    applyBtn.textContent = 'عرض النتائج';
    applyBtn.addEventListener('click', function () {
      haptic('light');
      state.filters = draft;
      closeSheet();
      push({ type: 'results', source: source, q: q });
    });
    sheet.appendChild(applyBtn);

    var clearAll = el('button', 'secondary-btn');
    clearAll.type = 'button';
    clearAll.textContent = 'مسح كل الفلاتر';
    clearAll.addEventListener('click', function () {
      haptic();
      draft = { lv: '', sb: '', tp: '', ac: '' };
      Array.prototype.forEach.call(sheet.querySelectorAll('.fchip.on'), function (n) { n.classList.remove('on'); });
      updateCount();
    });
    sheet.appendChild(clearAll);

    document.body.appendChild(sheet);
    sheetBackdrop.hidden = false;
    closeBtn.addEventListener('click', closeSheet);
    sheetBackdrop.addEventListener('click', closeSheet);
    updateCount();
  }

  function closeSheet() {
    var existing = document.querySelector('.sheet');
    if (existing) existing.remove();
    sheetBackdrop.hidden = true;
  }

  /* ─── favorites tab ─── */

  function renderFavs() {
    viewEl.innerHTML = '';

    var favs = filesByIds(favIds());
    viewEl.appendChild(sectionTitle('⭐ المفضلة (' + favs.length + ')'));

    if (!favs.length) {
      viewEl.appendChild(emptyBox('مفضلتك فارغة.<br>أضف الملفات عبر زر «☆ أضف للمفضلة» في صفحة الملف.'));
      return;
    }
    var list = el('div', 'file-list');
    favs.forEach(function (f) { list.appendChild(fileRow(f)); });
    viewEl.appendChild(list);
    viewEl.appendChild(el('div', 'detail-note', 'لإزالة ملف: افتحه ثم اضغط «★ في المفضلة».'));
  }

  /* ─── file details ─── */

  function crumbRow(catId) {
    var crumb = el('div', 'crumb');
    catPathNodes(catId).forEach(function (c, i) {
      if (i) crumb.appendChild(el('span', 'crumb-sep', '‹'));
      var seg = el('button', 'crumb-btn', c.name);
      seg.type = 'button';
      seg.addEventListener('click', function () {
        haptic();
        state.catFilter = 'all';
        push({ type: 'cat', id: c.id });
      });
      crumb.appendChild(seg);
    });
    return crumb;
  }

  function favShareRow(f) {
    var row = el('div', 'btn-row');

    var favB = el('button', 'secondary-btn' + (isFav(f.id) ? ' fav-on' : ''));
    favB.type = 'button';
    favB.textContent = isFav(f.id) ? '★ في المفضلة' : '☆ أضف للمفضلة';
    favB.addEventListener('click', function () {
      toggleFav(f.id);
      render();
    });
    row.appendChild(favB);

    var shareB = el('button', 'secondary-btn');
    shareB.type = 'button';
    shareB.textContent = '📤 مشاركة';
    shareB.addEventListener('click', function () { shareFile(f); });
    row.appendChild(shareB);

    return row;
  }

  function renderFileDetails(f) {
    viewEl.innerHTML = '';

    var box = el('div', 'detail-box');
    box.appendChild(coverEl(f, false));

    box.appendChild(el('div', 'detail-name', f.n));
    box.appendChild(el('div', 'detail-type', typeOf(f).label));

    var crumb = crumbRow(f.c);
    if (crumb.children.length) box.appendChild(crumb);

    var meta = metaLine(f);
    if (meta) box.appendChild(el('div', 'detail-path', meta));

    var access = fileAccess(f);
    var badge = {
      free: ['detail-badge badge-free', '🟢 مجاني — يُقرأ داخل التطبيق'],
      vip: ['detail-badge badge-vip', '🔒 حصري — محتوى EscuilaVIP'],
      bot: ['detail-badge badge-bot', '🤖 مجاني — يُسلَّم عبر البوت']
    }[access];
    box.appendChild(el('div', badge[0], badge[1]));

    if (access === 'free' && /^https:\/\/t\.me\//i.test(f.u)) {
      // telegram pages can't be framed — hand straight to the app
      var tgOpen = el('button', 'primary-btn');
      tgOpen.type = 'button';
      tgOpen.textContent = '📱 فتح في تيليجرام';
      tgOpen.addEventListener('click', function () { openTelegramUrl(f.u, true); });
      box.appendChild(tgOpen);
      box.appendChild(favShareRow(f));
    } else if (access === 'free') {
      var read = el('button', 'primary-btn');
      read.type = 'button';
      read.textContent = '👁️ قراءة داخل التطبيق';
      read.addEventListener('click', function () {
        haptic('light');
        push({ type: 'viewer', file: f });
      });
      box.appendChild(read);

      box.appendChild(favShareRow(f));

      var inBrowser = el('button', 'secondary-btn');
      inBrowser.type = 'button';
      inBrowser.textContent = '🌐 فتح في المتصفح';
      inBrowser.addEventListener('click', function () {
        haptic('light');
        if (tg && tg.openLink) tg.openLink(f.u);
        else window.open(f.u, '_blank');
      });
      box.appendChild(inBrowser);

      var inBot = el('button', 'secondary-btn');
      inBot.type = 'button';
      inBot.textContent = '🤖 عبر البوت';
      inBot.addEventListener('click', function () { openInBot(f); });
      box.appendChild(inBot);
    } else if (access === 'vip') {
      // same journey as the bot: show the VIP subscribe screen, bot enforces
      var how = el('button', 'primary-btn');
      how.type = 'button';
      how.textContent = '💎 كيف أحصل عليه؟';
      how.addEventListener('click', function () {
        haptic('light');
        push({ type: 'vip' });
      });
      box.appendChild(how);

      var open = el('button', 'secondary-btn');
      open.type = 'button';
      open.textContent = '🤖 طلب الملف من البوت';
      open.addEventListener('click', function () { openInBot(f); });
      box.appendChild(open);

      box.appendChild(favShareRow(f));

      box.appendChild(el('div', 'detail-note',
        'هذا الملف حصري لمشتركي EscuilaVIP. الاشتراك والتحقق والتسليم تتم داخل بوت Escuila — نفس النظام.'));
    } else {
      var botBtn = el('button', 'primary-btn');
      botBtn.type = 'button';
      botBtn.textContent = '🤖 استلام الملف من البوت';
      botBtn.addEventListener('click', function () { openInBot(f); });
      box.appendChild(botBtn);

      box.appendChild(favShareRow(f));

      box.appendChild(el('div', 'detail-note',
        'يتم تسليم هذا الملف داخل محادثة البوت مباشرة.'));
    }

    viewEl.appendChild(box);
  }

  /* ─── VIP screen — mirrors build_vip_subscribe_text/keyboard ─── */

  function renderVip() {
    viewEl.innerHTML = '';

    var box = el('div', 'detail-box vip-box');
    box.appendChild(el('div', 'detail-icon', '💎'));
    box.appendChild(el('div', 'detail-name', 'Escuila VIP'));
    box.appendChild(el('div', 'detail-type', 'اشتراك واحد — وصول كامل'));

    var feats = el('div', 'vip-feats');
    ['ملفات حصرية', 'تصحيحات منظمة', 'ملفات منسقة جاهزة', 'تنبيهات بالجديد', 'أولوية الدعم']
      .forEach(function (t) {
        var row = el('div', 'vip-feat', '✅ ' + t);
        feats.appendChild(row);
      });
    box.appendChild(feats);

    var prices = el('div', 'price-row');
    if (state.starsPrice > 0) {
      prices.appendChild(el('div', 'price-card',
        '⭐ النجوم\n' + state.starsPrice + ' Stars'));
    }
    if (state.madPrice > 0) {
      prices.appendChild(el('div', 'price-card',
        '💵 الدرهم\n' + state.madPrice + ' درهم'));
    }
    if (state.starsPrice > 0 || state.madPrice > 0) {
      box.appendChild(prices);
      box.appendChild(el('div', 'detail-note',
        'الأسعار تُقرأ من نظام البوت مباشرة — أي تغيير من لوحة الإدارة يظهر هنا تلقائياً.'));
    }

    var stars = el('button', 'primary-btn');
    stars.type = 'button';
    stars.textContent = state.starsPrice > 0
      ? '⭐ الدفع بالنجوم (' + state.starsPrice + ' ⭐)'
      : '⭐ الدفع بالنجوم — عبر البوت';
    stars.addEventListener('click', function () { openBotChat(''); });
    box.appendChild(stars);

    var manual = el('button', 'secondary-btn');
    manual.type = 'button';
    manual.textContent = '💵 CCP / PayPal — طلب يدوي';
    manual.addEventListener('click', function () { openBotChat('vip_request'); });
    box.appendChild(manual);

    var code = el('button', 'secondary-btn');
    code.type = 'button';
    code.textContent = '🎟 لدي كود اشتراك';
    code.addEventListener('click', function () { openBotChat(''); });
    box.appendChild(code);

    var contact = el('button', 'secondary-btn');
    contact.type = 'button';
    contact.textContent = '📞 تواصل مع الإدارة';
    contact.addEventListener('click', function () { openBotChat('vip_request'); });
    box.appendChild(contact);

    box.appendChild(el('div', 'detail-note',
      'الاشتراك والتحقق وتسليم المحتوى تتم داخل بوت Escuila — التطبيق والبوت نظام واحد.'));

    viewEl.appendChild(box);
  }

  /* ─── locked category ─── */

  function renderLockedInfo(c) {
    viewEl.innerHTML = '';

    var box = el('div', 'detail-box');
    box.appendChild(el('div', 'detail-icon', '🔒'));
    box.appendChild(el('div', 'detail-name', c.name));
    box.appendChild(el('div', 'detail-note',
      'هذا القسم حصري لأعضاء EscuilaVIP.\nالاشتراك يتم عبر نفس نظام البوت.'));

    var open = el('button', 'primary-btn');
    open.type = 'button';
    open.textContent = '💎 اشتراك EscuilaVIP';
    open.addEventListener('click', function () { push({ type: 'vip' }); });
    box.appendChild(open);

    var back = el('button', 'secondary-btn');
    back.type = 'button';
    back.textContent = '⬅️ متابعة التصفح';
    back.addEventListener('click', goBack);
    box.appendChild(back);

    viewEl.appendChild(box);
  }

  /* ─── embedded viewer ─── */

  function renderViewer(f) {
    viewEl.innerHTML = '';

    var wrap = el('div', 'viewer-wrap');

    var bar = el('div', 'viewer-bar');
    bar.appendChild(el('div', 'viewer-title', f.n));
    wrap.appendChild(bar);

    var stage = el('div', 'viewer-stage');

    var spinner = el('div', 'loading viewer-loading', '⏳ جارٍ فتح الملف…');
    stage.appendChild(spinner);

    var src = embedUrl(f.u);
    if (isImageUrl(f.u)) {
      var img = document.createElement('img');
      img.className = 'viewer-img';
      img.alt = f.n;
      img.onload = function () { spinner.hidden = true; };
      img.onerror = function () {
        spinner.hidden = true;
        hint.textContent = '⚠️ تعذّر تحميل الصورة — جرّب زر الفتح في المتصفح.';
        hint.hidden = false;
      };
      img.src = f.u;
      stage.appendChild(img);
    } else if (src) {
      var frame = document.createElement('iframe');
      frame.className = 'viewer-frame';
      frame.setAttribute('allow', 'autoplay; fullscreen');
      frame.referrerPolicy = 'no-referrer';
      // X-Frame-Options refusals are invisible to JS: onload may still fire,
      // so the fallback buttons below stay visible in every case.
      frame.onload = function () { setTimeout(function () { spinner.hidden = true; }, 400); };
      frame.src = src;
      stage.appendChild(frame);
    } else {
      spinner.hidden = true;
    }
    wrap.appendChild(stage);

    var hint = el('div', 'viewer-hint',
      'لا يظهر شيء؟ بعض المصادر تمنع العرض المدمج — استخدم الأزرار أدناه.');
    hint.hidden = true;
    wrap.appendChild(hint);

    var actions = el('div', 'viewer-actions');
    var inBrowser = el('button', 'primary-btn');
    inBrowser.type = 'button';
    inBrowser.textContent = '🌐 فتح في المتصفح';
    inBrowser.addEventListener('click', openExternal);
    actions.appendChild(inBrowser);

    var inBot = el('button', 'secondary-btn');
    inBot.type = 'button';
    inBot.textContent = '🤖 عبر البوت';
    inBot.addEventListener('click', function () { openInBot(f); });
    actions.appendChild(inBot);
    wrap.appendChild(actions);

    viewEl.appendChild(wrap);

    // native MainButton = "open in browser" while the viewer is on screen
    setMainButton('🌐 فتح في المتصفح', openExternal);

    // slow-source nudge: after 6s point the user at the fallback buttons
    setTimeout(function () {
      if (!spinner.hidden) {
        hint.hidden = false;
      }
    }, 6000);

    function openExternal() {
      haptic('light');
      if (tg && tg.openLink) tg.openLink(f.u);
      else window.open(f.u, '_blank');
    }
  }

  /* ─── deep links from the bot (startapp=cat_<id> / file_<id>) ─── */

  function handleStartParam(sp) {
    var m = /^file_(\d+)$/.exec(sp || '');
    if (m) {
      var f = state.fileById[+m[1]];
      if (f) {
        recordRecent(f.id);
        state.stack = [{ type: 'home' }, { type: 'file', file: f }];
        render();
        return;
      }
      showToast('الملف غير متوفر بعد — اضغط 🔄 تحديث في المكتبة');
    }
    m = /^cat_(\d+)$/.exec(sp || '');
    if (m) {
      var c = catById(+m[1]);
      if (c && !c.locked) {
        state.stack = [{ type: 'home' }, { type: 'cat', id: c.id }];
        render();
        return;
      }
      if (c && c.locked) {
        state.stack = [{ type: 'home' }, { type: 'locked', cat: c }];
        render();
        return;
      }
      showToast('القسم غير متوفر بعد — اضغط 🔄 تحديث في المكتبة');
    }
  }

  /* ─── events ─── */

  searchEl.addEventListener('input', function () {
    clearEl.hidden = !searchEl.value;
    clearTimeout(state.searchTimer);
    state.searchTimer = setTimeout(function () {
      state.query = searchEl.value.trim();
      if (!state.query) {
        state.stack = [{ type: 'search' }];
        state.tab = 'search';
        updateTabbar();
        render();
        return;
      }
      state.tab = 'search';
      state.stack = [{ type: 'search' }];
      updateTabbar();
      render();
    }, 220);
  });

  clearEl.addEventListener('click', function () {
    searchEl.value = '';
    clearEl.hidden = true;
    state.query = '';
    switchTab('search', { noFocus: true });
    searchEl.focus();
  });

  tabButtons.forEach(function (btn) {
    btn.addEventListener('click', function () {
      var tab = btn.getAttribute('data-tab');
      if (tab === 'search') {
        switchTab('search');
      } else {
        switchTab(tab, { noFocus: true });
      }
    });
  });

  // registered ONCE here — re-registering inside render() stacked duplicate
  // listeners, making one back-press pop several views
  if (tg && tg.BackButton) {
    tg.BackButton.onClick(function () { goBack(); });
  }

  /* ─── boot ─── */

  function fail(msg) {
    viewEl.innerHTML = '';
    var box = el('div', 'error-box');
    box.appendChild(el('div', null, '⚠️ ' + msg));
    var retry = el('button', null, 'إعادة المحاولة');
    retry.type = 'button';
    retry.addEventListener('click', boot);
    box.appendChild(retry);
    viewEl.appendChild(box);
  }

  function showSkeleton() {
    viewEl.innerHTML = '';
    for (var i = 0; i < 6; i++) viewEl.appendChild(el('div', 'skel skel-card'));
  }

  function applyColorScheme() {
    try {
      document.body.classList.toggle('dark', !!(tg && tg.colorScheme === 'dark'));
      if (tg && tg.onEvent) {
        tg.onEvent('themeChanged', function () {
          document.body.classList.toggle('dark', tg.colorScheme === 'dark');
        });
      }
    } catch (e) { /* noop */ }
  }

  function fetchJSON(url) {
    return fetch(url).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    });
  }

  // Try data/ first, then repo root (GitHub upload sometimes flattens folders).
  // v is the exported data version: identical v hits the browser cache, so
  // repeat opens cost nothing until the next export bumps it.
  function fetchFirst(file, v) {
    var q = '?v=' + v;
    return fetchJSON('data/' + file + q).catch(function () {
      return fetchJSON(file + q);
    });
  }

  function boot() {
    showSkeleton();
    applyColorScheme();
    // settings.json is tiny — fetched fresh (unique URL) to learn the data
    // version; the big files then reuse the browser cache until next export
    fetchJSON('data/settings.json?v=' + Date.now())
      .catch(function () { return fetchJSON('settings.json?v=' + Date.now()); })
      .catch(function () {
        return { bot_username: '', version: 0, stars_price: 0, mad_price: 0 };
      })
      .then(function (s) {
        state.botUsername = s.bot_username || '';
        state.starsPrice = parseInt(s.stars_price, 10) || 0;
        state.madPrice = parseInt(s.mad_price, 10) || 0;
        var v = s.version || Date.now();
        return Promise.all([
          fetchFirst('categories.json', v),
          fetchFirst('files.json', v)
        ]);
      })
      .then(function (res) {
        state.cats = res[0].categories || [];
        state.files = res[1].files || [];
        state.fileById = {};
        state.files.forEach(function (f) { state.fileById[f.id] = f; });
        state.stack = [{ type: 'home' }];
        state.tab = 'home';
        state.catFilter = 'all';
        render();
        updateTabbar();
        syncFavsFromCloud();
        // deep link from the bot (startapp=cat_<id> / file_<id>) — once
        if (!state.startParamDone) {
          state.startParamDone = true;
          try {
            var sp = tg && tg.initDataUnsafe ? tg.initDataUnsafe.start_param : null;
            if (sp) handleStartParam(String(sp));
          } catch (e) { /* older clients */ }
        }
      })
      .catch(function () {
        fail(navigator.onLine === false
          ? 'لا يوجد اتصال بالإنترنت — تحقق من الشبكة ثم أعد المحاولة.'
          : 'حدث خطأ أثناء تحميل البيانات');
      });
  }

  boot();
})();
